#!/bin/bash

ARGS=(`getopt --options h --long help -- "$@"`)

if [ $? -ne 0 ];
then
	echo "To get some help use: installall -h"
	exit 2
fi

for i in ${ARGS}
do
	case $i in
		(-h|--help) cat `dirname $0`/INSTALL; exit 0;; 
	esac
done

source ../scripts/COMPILE_FLAG

echo 
echo "Install japet"
echo "============="

make reset --silent 
if make --silent
then	
	echo -e "\nSuccess compiling japet\n"
	exit 0
else 
	echo -e "\nFail to compile japet\n"
	exit 1
fi
